server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer
      properties:
        partition.assignment.strategy: "org.apache.kafka.clients.consumer.StickyAssignor"
        #group.instance.id: 1